//
//  XYDFoundation.h
//  XYDCategories
//
//  Created by Jakey on 16/5/29.
//  Copyright © 2016年 www.skyfox.org. All rights reserved.
//

#ifndef XYDFoundation_h
#define XYDFoundation_h

#import "NSArray+XYDBlock.h"
#import "NSArray+XYDSafeAccess.h"
#import "NSBundle+XYDAppIcon.h"
#import "NSData+XYDAPNSToken.h"
#import "NSData+XYDBase64.h"
#import "NSData+XYDDataCache.h"
#import "NSData+XYDEncrypt.h"
#import "NSData+XYDGzip.h"
#import "NSData+XYDHash.h"
#import "NSData+XYDzlib.h"
#import "NSData+XYDPCM.h"
#import "NSDate+XYDCupertinoYankee.h"
#import "NSDate+XYDExtension.h"
#import "NSDate+XYDFormatter.h"
#import "NSDate+XYDInternetDateTime.h"
#import "NSDate+XYDReporting.h"
#import "NSDate+XYDUtilities.h"
#import "NSDateFormatter+XYDMake.h"
#import "NSDecimalNumber+XYDCalculatingByString.h"
#import "NSDecimalNumber+XYDExtensions.h"
#import "NSDictionary+XYDBlock.h"
#import "NSDictionary+XYDJSONString.h"
#import "NSDictionary+XYDMerge.h"
#import "NSDictionary+XYDSafeAccess.h"
#import "NSDictionary+XYDURL.h"
#import "NSDictionary+XYDXML.h"
#import "NSException+XYDTrace.h"
#import "NSFileHandle+XYDReadLine.h"
#import "NSFileManager+XYDPaths.h"
#import "NSHTTPCookieStorage+XYDFreezeDry.h"
#import "NSIndexPath+XYDOffset.h"
#import "NSInvocation+XYDBb.h"
#import "NSInvocation+XYDBlock.h"
#import "NSMutableURLRequest+XYDUpload.h"
#import "NSNotificationCenter+XYDMainThread.h"
#import "NSNumber+XYDCGFloat.h"
#import "NSNumber+XYDRomanNumerals.h"
#import "NSNumber+XYDRound.h"
#import "NSObject+XYDAddProperty.h"
#import "NSObject+XYDAppInfo.h"
#import "NSObject+XYDAssociatedObject.h"
#import "NSObject+XYDAutoCoding.h"
#import "NSObject+XYDBlocks.h"
#import "NSObject+XYDBlockTimer.h"
#import "NSObject+XYDEasyCopy.h"
#import "NSObject+XYDGCD.h"
#import "NSObject+XYDKVOBlocks.h"
#import "NSObject+XYDReflection.h"
#import "NSObject+XYDRuntime.h"
#import "NSRunLoop+XYDPerformBlock.h"
#import "NSSet+XYDBlock.h"
#import "NSString+XYDBase64.h"
#import "NSString+XYDContains.h"
#import "NSString+XYDDictionaryValue.h"
#import "NSString+XYDEmoji.h"
#import "NSString+XYDEncrypt.h"
#import "NSString+XYDHash.h"
#import "NSString+XYDMatcher.h"
#import "NSString+XYDMIME.h"
#import "NSString+XYDNormalRegex.h"
#import "NSString+XYDPinyin.h"
#import "NSString+XYDRemoveEmoji.h"
#import "NSString+XYDScore.h"
#import "NSString+XYDSize.h"
#import "NSString+XYDTrims.h"
#import "NSString+XYDURLEncode.h"
#import "NSString+XYDUUID.h"
#import "NSString+XYDXMLDictionary.h"
#import "NSString+XYDStringPages.h"
#import "NSTimer+XYDAddition.h"
#import "NSTimer+XYDBlocks.h"
#import "NSURL+XYDParam.h"
#import "NSURL+XYDQueryDictionary.h"
#import "NSURLConnection+XYDSelfSigned.h"
#import "NSURLRequest+XYDParamsFromDictionary.h"
#import "NSUserDefaults+XYDiCloudSync.h"
#import "NSUserDefaults+XYDSafeAccess.h"

#endif /* XYDFoundation_h */
